smart_ip_ip2location_bin_db.settings:
  type: config_object
  label: 'Smart IP IP2Location binary database settings'
  mapping:
    version:
      type: string
      label: 'IP2Location binary database version: licensed or free.'
    edition:
      type: string
      label: 'IP2Location product edition: DB1 to DB24.'
    token:
      type: string
      label: 'IP2Location download token.'
    db_auto_update:
      type: boolean
      label: 'Automatic IP2Location binary database update.'
    caching_method:
      type: string
      label: 'IP2Location caching method.'
    bin_file_custom_path:
      type: string
      label: 'IP2Location binary database custom path.'
