smart_ip.settings:
  type: config_object
  label: 'Smart IP settings'
  mapping:
    data_source:
      type: string
      label: 'The primary data source.'
    roles_to_geolocate:
      type: sequence
      label: 'Maps each role to itself on whether to geolocate or not.'
      sequence:
        type: string
        label: 'Geolocation flag per role.'
    save_user_location_creation:
      type: boolean
      label: 'Flag determines if location details is saved per user in their profile upon registration.'
    roles_in_debug_mode:
      type: sequence
      label: 'Maps each role to boolean on whether to use debug mode or not.'
      sequence:
        type: boolean
        label: 'Debug mode per role.'
    roles_in_debug_mode_ip:
      type: sequence
      label: 'Maps roles to debug mode IP address.'
      sequence:
        type: string
        label: 'Debug IP address per role.'
    allowed_pages:
      type: text
      label: "The allowed specific Drupal native pages to acquire/update user's geolocation."
    eu_visitor_dont_save:
      type: boolean
      label: 'Flag for preventing to save location details of visitors from EU countries.'
    timezone_format:
      type: string
      label: 'Time zone format.'
