smart_ip_maxmind_geoip2_bin_db.settings:
  type: config_object
  label: 'Smart IP MaxMind GeoIP2 binary database settings'
  mapping:
    version:
      type: string
      label: 'MaxMind GeoIP2 binary database version whether licensed or lite.'
    edition:
      type: string
      label: 'MaxMind GeoIP2 binary database edition whether city or country.'
    license_key:
      type: string
      label: 'MaxMind GeoIP2 license key.'
    db_auto_update:
      type: boolean
      label: 'Automatic MaxMind GeoIP2 binary database update.'
    bin_file_custom_path:
      type: string
      label: 'MaxMind GeoIP2 binary database custom path.'