smart_ip_maxmind_geoip2_web_service.settings:
  type: config_object
  label: 'Smart IP MaxMind GeoIP2 Precision web service settings'
  mapping:
    service_type:
      type: string
      label: 'MaxMind GeoIP2 Precision web services whether country, city or insights.'
    user_id:
      type: string
      label: 'MaxMind GeoIP2 Precision user ID.'
    license_key:
      type: string
      label: 'MaxMind GeoIP2 Precision license key.'