<?php

/**
 * @file
 * Contains mainblockblogsection.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mainblockblogsection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bmi quiz module.
    case 'help.page.mainblockblogsection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module which Main Blog Section') . '</p>';
      return $output;

    default:
  }
}

function mainblockblogsection_theme($existing, $type, $theme, $path) {
  return [
    'my_blognew' => [
      'variables' => [
	  	'blogid' => NULL,
	  	'ipaddressblog' => NULL,
        'popup_session' => NULL,
		],
    ],
  ];
}
