smart_ip_ipinfodb_web_service.settings:
  type: config_object
  label: 'Smart IP IPInfoDB web service settings'
  mapping:
    version:
      type: integer
      label: 'IPInfoDB API version.'
    api_key:
      type: string
      label: 'IPInfoDB API key.'