device_geolocation.settings:
  type: config_object
  label: 'Device Geolocation settings'
  mapping:
    use_ajax_check:
      type: boolean
      label: "Flag to enable to use AJAX in user's geolocation checking."
    frequency_check:
      type: float
      label: "Number of hours will prompt the user for geolocation."
    google_map_api_key:
      type: string
      label: 'Google map API key.'
    google_map_region:
      type: string
      label: 'Google map region.'
    google_map_language:
      type: string
      label: 'Google map localization.'

